[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.curl", "php83Extensions.tokenizer", "php83Extensions.bcmath", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build"]

[phases.deploy]
cmds = ["php artisan migrate --force --seed", "php artisan config:cache", "php artisan route:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"